export const routes = {
    home: '/',
    signIn: '/sign-in',
    signUp: '/sign-up',
    admin: '/admin/:id',
    user: '/user/:id',
    hr: '/hr/:id',
    register: '/register/:id/:token',
    resetPassword: '/reset-password',
    setNewPassword: '/reset-password/:token',
    registerUser: '/register/:id/:token',
    accountHr: '/hr/:id/account',
    accountUser: '/user/:id/account',
    accountAdmin: '/admin/:id/account',
    cv: '/cv/:id/:email',
    notFound: '*',
};
