export const ENDPOINTS = {
    signIn: '/auth/login',
    signOut: '/auth/logout',
    register: '/user/{userId}/{token}',
    resetPassword: '/auth/reset-password',
    updatePassword: '/auth/update-password',
    changePassword: '/auth/change-password',
    sendHrForm: '/admin/register-hr',
    validateCsv: '/admin/validate-csv',
    saveCsv: '/admin/save-csv',
    setStatus: '/hr/status',
    filter: '/hr/filter',
    search: '/hr/search',
    cv: '/hr/user',
};
