export const defaultValues = {
    email: '',
    phone: '',
    firstName: '',
    lastName: '',
    githubUsername: '',
    portfolioUrls: [''],
    projectUrls: ['', ''],
    bio: '',
    expectedTypeWork: 'Bez znaczenia',
    targetWorkCity: '',
    expectedContractType: 'Brak preferencji',
    expectedSalary: '',
    canTakeApprenticeship: 'NIE',
    monthsOfCommercialExp: 0,
    education: '',
    workExperience: '',
    courses: '',
};
